server:
  port: 6001
  tomcat:
    max-connections:  1000 # 最大连接数
    accept-count: 1500  #
  connection-timeout: 60000   # 连接超时设置

# ribbon set connection  timeout and  readtimeout
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wsp
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mika_admin?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource  #上传文件大小配置
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
  redis:
    host: 127.0.0.1
    port: 6379
    password:


redis:
  cache:
    expiration: 3600

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.pig.admin.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


